# application: pythonattack
# version: 1
# runtime: python27
# api_version: 1
# threadsafe: true

# handlers:
# - url: /.*
#   script: pythonAttack.py


runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: pythonAttack.app